### PR TITLE
Matt revenue report

### PR DESCRIPTION
**Pull request by augsismyburger**
## REFERENCE

Ticket (syntax: #Number, ex. #1)

[ERD](https://github.com/Phat-Taupe-Pests/Bangazon) 

## DESCRIPTION
What did you do? Why did you do it?
Added a method for Getting completed orders for the selected customer
Added the CLI to display this data
Formatted the CLI to look bitchin'

## STEPS TO TEST
1. Clone this branch to a local repo
2. Run `dotnet restore`
3. Test functionality
	* cd into bangazon.tests and `dotnet test` --- All tests should pass
	* cd back and into the bangazon directory --- `dotnet run`
	* Choose option `10` and insure a dopereport is displayed

### CODE REVIEW

**Comment by adamreidelbach** [comment]
👍 Works for me

**Comment by elizawmeeks** [comment]
looks good.

**Comment by chazhenricks** [comment]
Clear revenue report before each call to get a new revenue report

**Comment by chazhenricks** [comment]
Otherwise FIYA

**Pull request merged**
