### PR TITLE
Input scrubbed Customer

### PR DESCRIPTION
**Pull request by elizawmeeks**
## REFERENCE

Ticket #1 

[ERD](https://github.com/Phat-Taupe-Pests/Bangazon) 

## DESCRIPTION
Input scrubbed option number 1, entering a customer.

## STEPS TO TEST
1. Clone this branch to a local repo
2. CD into `Bangazon` and run `dotnet run`
3. Select option one and try to get it to throw and exception.

### CODE REVIEW

**Comment by augsismyburger** [comment]
Werks. 👍

**Comment by adamreidelbach** [comment]
Exception thrown at postal code

**Comment by chazhenricks** [comment]
Able to add numbers for names as well as state for adding new customer

**Comment by BSGreaves** [comment]
Put on hold till further notice

**Comment by augsismyburger** [comment]
soooooooooooo good.

**Pull request merged**
