### PR TITLE
Chaz order pop

### PR DESCRIPTION
**Pull request by chazhenricks**
## REFERENCE

Ticket (#11)

[ERD](https://github.com/Phat-Taupe-Pests/Bangazon) 

## DESCRIPTION
Formatting for the Popularity Report. 
Contains dummy data as of now. 

## STEPS TO TEST
1. Clone this branch to a local repo
2. Run `dotnet restore`
3. Run `cd bangazon` and then `dotnet run`
	*press `11` then hit enter
	* bask in my glory

### CODE REVIEW

**Comment by elizawmeeks** [comment]
looks goo--
annihilatedbythesun

**Comment by augsismyburger** [comment]
SWASS 👍

**Comment by augsismyburger** [comment]
works on my machine. 👍

**Comment by BSGreaves** [comment]
https://i.ytimg.com/vi/eHgNXBP_Jwc/maxresdefault.jpg

**Pull request merged**
